# Generated by Django 3.0.7 on 2020-06-15 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.IntegerField(db_column='room_id', primary_key=True, serialize=False)),
                ('beds_count', models.IntegerField(db_column='beds_count')),
                ('floor_number', models.IntegerField(db_column='floor_number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'room',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(db_column='service_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('Description', models.TextField(db_column='description', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'service',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room')),
                ('services', models.ManyToManyField(to='hotel.Service')),
            ],
            options={
                'db_table': 'reservation',
                'managed': True,
            },
        ),
    ]
